---
name: "Disable User Data"
guid: "b24c5930-c337-4e0f-977f-1d900629ad09"
version: "0.2.1.2"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Disables user data in certain API calls"
description: >
  Disables user data in configurable API points in order
  to speed up queries
category: "General"
owner: "pelluch"
artifacts:
- "Jellyfin.Plugin.DisableUserData.dll"
changelog: >
  changelog
